name: Daily Selenium Run

on:
  schedule:
    # 12:50 PM Turkey time = 09:50 UTC
    - cron: '*/30 * * * *'
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable
          sudo apt-get install -y chromium-chromedriver
          which chromedriver
          chromedriver --version        

      - name: Run Selenium script
        run: |
          python iftar.py > output.log 2>&1 || (cat output.log && exit 1)

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-logs
          path: output.log
