name: Daily Selenium Run

on:
  schedule:
    # 12:50 PM Turkey time = 09:50 UTC
    - cron: '10 10 * * *'
  workflow_dispatch:  

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Chrome and ChromeDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install -y ./google-chrome-stable_current_amd64.deb
          CHROME_VERSION=$(google-chrome --version | awk '{print $3}')
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE")
          wget https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/  

      - name: Run Selenium script
        run: |
          python iftar.py > output.log 2>&1
          cat output.log

      - name: Upload logs as artifact
        uses: actions/upload-artifact@v4
        with:
          name: selenium-logs
          path: output.log
